#version 430

struct Particle{
    vec4 position;
    vec4 velocity;
    vec4 origin;
};
uniform float deltaTime;
layout(std430, binding = 5) buffer particle_data{
    Particle particles[ ]; 
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main(){
    uint globalID = gl_GlobalInvocationID.x;
    
    particles[globalID].position.xyz += particles[globalID].velocity.xyz * deltaTime;
}
